export interface OpportunityModel{
    id?:number,
    ruc:number,
    businessName:string,
    SfaNumber:number,
    oppSfaDateCreation:Date|string,
    type:string,
    product:string,
    productType:string,
    otherDetails:string,
    createdAt:Date|string,
    updatedAt:Date|string
    state:string,
    estimatedClosingDate:Date|string,
    commentary:string,
    contactName?:string,
    contactNumber?:string,
    userAssigned?:string,
    amount?:number
    units:number
}